### savePerson
POST http://localhost:8080/save-person
Content-Type: application/json

{
  "userName": "hjf",
  "pet": {
    "name": "jerry",
    "weight": 3.0
  }
}

### 500error 返回json格式，页面打开浏览器查看
GET http://localhost:8080/error5xx
Content-Type: application/json

### 400eror 返回json格式，页面打开浏览器查看
GET http://localhost:8080/page_not_found
Accept: application/json

### selectUser 指定
GET http://localhost:8080/select-user?page=1&count=2
Accept: application/json

### selectUser 默认值
GET http://localhost:8080/select-user
Accept: application/json